// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SpaceXLaunchData.Data;
using System;

namespace SpaceXLaunchData.Migrations
{
    [DbContext(typeof(SpaceXLaunchDataDbContext))]
    [Migration("20180523042007_AddedRocketResult")]
    partial class AddedRocketResult
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpaceXLaunchData.Models.Launch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Details");

                    b.Property<DateTime>("LaunchDate");

                    b.Property<string>("Manifest");

                    b.Property<bool>("Result");

                    b.Property<string>("RocketName");

                    b.Property<string>("RocketResult");

                    b.HasKey("ID");

                    b.ToTable("Launches");
                });
#pragma warning restore 612, 618
        }
    }
}
